# Generated by Django 6.1.1 on 2026-10-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('event', models.CharField(max_length=32)),
                ('lang', models.CharField(blank=True, max_length=8)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('day', 'event', 'lang'), name='funnel_day_event_lang')],
            },
        ),
    ]
