# Generated by Django 6.0.5 on 2026-06-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_address', models.CharField(max_length=512, unique=True, verbose_name='нормализованный адрес')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lng', models.FloatField(verbose_name='долгота')),
                ('formatted_address', models.CharField(max_length=512, verbose_name='formatted адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
