# Generated by Django 6.0.5 on 2026-06-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_geocodecache_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=32, verbose_name='метрика')),
                ('period', models.CharField(max_length=7, verbose_name='период (YYYY-MM)')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='счётчик')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('metric', 'period'), name='uniq_usage_metric_period')],
            },
        ),
    ]
