# Generated by Django 6.0.5 on 2026-06-04 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0003_delivery_eta_at_delivery_eta_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('on_the_way', 'U dostavi'), ('rating_request', 'Ocena')], max_length=16)),
                ('channel', models.CharField(blank=True, choices=[('viber', 'Viber'), ('sms', 'SMS')], max_length=6)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('logical_message_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('sent', 'sent'), ('delivered', 'delivered'), ('read', 'read'), ('failed', 'failed')], default='queued', max_length=10)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='deliveries.delivery')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'on_the_way')), fields=('delivery',), name='uniq_on_the_way_per_delivery')],
            },
        ),
    ]
