# Generated by Django 6.0.5 on 2026-06-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0011_alter_delivery_options'),
        ('notifications', '0002_optout'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('viber', 'Viber'), ('sms', 'SMS')], max_length=16)),
                ('ok', models.BooleanField(default=False)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['attempt_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('delivery', 'kind', 'logical_message_id'), name='uniq_logical_message_per_delivery_kind'),
        ),
        migrations.AddField(
            model_name='notificationattempt',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='notifications.notification'),
        ),
    ]
