# Generated by Django 6.1.1 on 2026-09-28 19:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_shop_send_limits'),
        ('notifications', '0005_telegramcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон (E.164)')),
                ('kind', models.CharField(choices=[('on_the_way', 'on_the_way'), ('resend', 'resend'), ('rating_request', 'rating_request')], max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='deliveries.delivery')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_sends', to='deliveries.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'created_at'], name='outbound_shop_created'), models.Index(fields=['phone', 'created_at'], name='outbound_phone_created'), models.Index(fields=['delivery', 'kind'], name='outbound_delivery_kind')],
            },
        ),
    ]
