# Generated by Django 6.0.5 on 2026-06-04 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='имя получателя')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='телефон (E.164)')),
                ('phone_risk', models.BooleanField(default=False, verbose_name='флаг риска номера')),
                ('dest_address', models.CharField(max_length=300, verbose_name='адрес назначения')),
                ('dest_lat', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('dest_lng', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='описание')),
                ('source', models.CharField(choices=[('manual', 'manual'), ('api', 'api')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Spremno'), ('on_the_way', 'U dostavi'), ('delivered', 'Završeno')], default='created', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='deliveries.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
