# Generated by Django 6.0.5 on 2026-06-04 14:45

import deliveries.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='eta_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETA (UTC)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='eta_source',
            field=models.CharField(blank=True, max_length=6, verbose_name='источник ETA'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='старт доставки'),
        ),
        migrations.CreateModel(
            name='TrackingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=deliveries.models._new_tracking_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_token', to='deliveries.delivery')),
            ],
        ),
    ]
