# Generated by Django 6.0.5 on 2026-06-06 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_alter_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, max_length=16, verbose_name='префикс')),
                ('key_hash', models.CharField(max_length=64, unique=True, verbose_name='sha256 хэш ключа')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='метка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='последнее использование')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='отозван')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='deliveries.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Idempotency-Key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='deliveries.delivery')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='deliveries.shop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shop', 'key'), name='uniq_idempotency_key_per_shop')],
            },
        ),
    ]
