# Generated by Django 6.0.5 on 2026-06-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_apikey_apiidempotencykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=200, verbose_name='секрет вебхука (HMAC)'),
        ),
        migrations.AddField(
            model_name='shop',
            name='webhook_url',
            field=models.URLField(blank=True, verbose_name='URL вебхука'),
        ),
    ]
