# Generated by Django 6.0.5 on 2026-06-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0010_shop_webhook_secret_shop_webhook_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['created_at']},
        ),
    ]
