# Generated by Django 6.1.1 on 2026-09-28 19:57

from django.db import migrations, models


def grandfather_existing_shops(apps, schema_editor):
    # SERBITO-345: магазины, заведённые до лимитов, — известные клиенты; пробный режим
    # только для новых регистраций. Список всё равно стоит просмотреть в админке.
    apps.get_model("deliveries", "Shop").objects.update(sending_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0011_alter_delivery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='daily_send_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='лимит сообщений в день'),
        ),
        migrations.AddField(
            model_name='shop',
            name='monthly_send_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='лимит сообщений в месяц'),
        ),
        migrations.AddField(
            model_name='shop',
            name='sending_verified',
            field=models.BooleanField(default=False, help_text='Снимает пробные лимиты: обычные дневной/месячный лимиты и любые номера.', verbose_name='проверен для отправки'),
        ),
        migrations.RunPython(grandfather_existing_shops, migrations.RunPython.noop),
    ]
