# Generated by Django 6.1.1 on 2026-10-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_shop_send_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='recipient_language',
            field=models.CharField(choices=[('sr-latn', 'Srpski'), ('en', 'English')], default='sr-latn', max_length=10, verbose_name='язык получателя'),
        ),
    ]
