# Generated by Django 6.1.1 on 2026-10-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0013_delivery_recipient_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='телефон для клиентов'),
        ),
    ]
