# Generated by Django 6.1.1 on 2026-10-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0014_shop_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='доставлена'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pii_purged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='персональные данные стёрты'),
        ),
    ]
